spring.application.name=restaurant-management-service

spring.datasource.url=jdbc:postgresql://localhost:5433/orderly_db
spring.datasource.username=admin
spring.datasource.password=adminpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

server.port=8080
